services:
  gg-backend:
    image: "ghcr.io/adamskye/gg-backend"
    volumes:
      - ./backend-uploads:/app/uploaded_files
    environment:
      - GRANITE_MODEL=granite4:350m
      - OLLAMA_HOST=ollama:11434

  gg-frontend:
    image: "ghcr.io/adamskye/gg-frontend"

  caddy:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy-data:/data
      - caddy-config:/config

  ollama:
      image: ollama/ollama:latest
      volumes:
        - ollama:/root/.ollama
        # - ./run_ollama.sh:/scripts/run_ollama.sh:Z
      ports:
        - "11434:11434"
      # entrypoint: ["/bin/sh", "/scripts/run_ollama.sh"]

volumes:
  caddy-data:
  caddy-config:
  ollama:
