services:
  gg-backend:
    build: ../Backend
    environment:
      - GRANITE_MODEL=granite4:350m
      - OLLAMA_HOST=ollama:11434

  gg-frontend:
    build: ../Frontend

  caddy:
    image: caddy:latest
    ports:
      - "8080:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy-data:/data
      - caddy-config:/config

  ollama:
      image: ollama/ollama:latest
      volumes:
        - ollama:/root/.ollama
      ports:
        - "11434:11434"

volumes:
  caddy-data:
  caddy-config:
  ollama:
